OTP-PKIX {iso(1) identified-organization(3) dod(6) internet(1)
	private(4) enterprices(1) ericsson(193) otp(19) ssl(10)
	pkix1(1)}

DEFINITIONS EXPLICIT TAGS ::=

BEGIN

-- EXPORTS ALL

IMPORTS
        Extensions{}
        FROM PKIX-CommonTypes-2009

	CertificateSerialNumber, Name, CertExtensions{}
	FROM PKIX1Implicit-2009
       	{iso(1) identified-organization(3) dod(6) internet(1) security(5)
       	mechanisms(5) pkix(7) id-mod(0) id-mod-pkix1-implicit-02(59)}

       Validity, Version, SubjectPublicKeyInfo, SignatureAlgorithms,
       UniqueIdentifier
       FROM PKIX1Explicit-2009
       {iso(1) identified-organization(3) dod(6) internet(1)
       	security(5) mechanisms(5) pkix(7) id-mod(0)
      	id-mod-pkix1-explicit-02(51)}

	--Keys and Signatures
	AlgorithmIdentifier{}, SIGNATURE-ALGORITHM
	FROM AlgorithmInformation-2009
	{iso(1) identified-organization(3) dod(6) internet(1) security(5)
	mechanisms(5) pkix(7) id-mod(0)
	id-mod-algorithmInformation-02(58)};
--
-- Certificate
--

OTPCertificate  ::=  SEQUENCE  {
     tbsCertificate       OTPTBSCertificate,
     signatureAlgorithm    AlgorithmIdentifier{SIGNATURE-ALGORITHM,
                                    { SignatureAlgorithms }},
     signature            BIT STRING  }

OTPTBSCertificate  ::=  SEQUENCE  {

     version         [0]  Version DEFAULT v1,
     serialNumber         CertificateSerialNumber,
     signature            AlgorithmIdentifier{SIGNATURE-ALGORITHM,
                                    { SignatureAlgorithms }},
     issuer               Name,
     validity             Validity,
     subject              Name,
     subjectPublicKeyInfo SubjectPublicKeyInfo,
     ... ,
      [[2:               -- If present, version MUST be v2
      issuerUniqueID  [1]  IMPLICIT UniqueIdentifier OPTIONAL,
      subjectUniqueID [2]  IMPLICIT UniqueIdentifier OPTIONAL
      ]],
      [[3:               -- If present, version MUST be v3 --
      extensions      [3]  Extensions{{CertExtensions}} OPTIONAL
      ]], ... }

 -- We accept utf8String encoding of the US-ASCII
 -- country name code and the mix up with other country code systems
 -- that uses three characters instead of two.

 OTP-X520countryname ::= CHOICE {
       printableString   PrintableString (SIZE (2..3)),
       utf8String        UTF8String      (SIZE (2..3))
}

-- Used to workaround that some CAs create too long User Notices

OTPUserNotice ::= SEQUENCE {
     noticeRef        OTPNoticeReference OPTIONAL,
     explicitText     OTPDisplayText OPTIONAL}

OTPNoticeReference ::= SEQUENCE {
     organization     OTPDisplayText,
     noticeNumbers    SEQUENCE OF INTEGER }

OTPDisplayText ::= CHOICE {
     ia5String        IA5String      (SIZE (1..350)),
     visibleString    VisibleString  (SIZE (1..350)),
     bmpString        BMPString      (SIZE (1..350)),
     utf8String       UTF8String     (SIZE (1..350)) }

END
